/*
 * LoginGUI.java
 *
 * Created on 2020-09-17
 *
 * Copyright (C) 2020 Volkswagen AG, All rights reserved.
 */

package gui_v3;

import java.awt.*;

import javax.swing.*;

import atm.ATM;

public class LoginGUI extends GUI_v3 {
    private JPanel mainPanel;
    private JTextField textField;
    private JPasswordField passwordField;
    private JButton loginButton;

    public LoginGUI(ATM atm, JFrame parentFrame) throws HeadlessException {

        super(parentFrame, atm);

        add(mainPanel);

        setSize(300, 300);

        setDefaultCloseOperation(EXIT_ON_CLOSE);

        loginButton.addActionListener(e -> login());
    }

    private void login() {

        if (getAtm().login(textField.getText(), passwordField.getText())) {

            MainGUI mainGUI = new MainGUI(getAtm(), this);

            setVisible(false);
        } else {

            showErrorDialog("Invalid credentials", "Password or Iban invalid");
        }

        textField.setText("");
        passwordField.setText("");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }
    /**
     * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR call it in your
     * code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("IBAN");
        mainPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 2, 1,
                                                                               com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                                                                               com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                                                                               com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                               com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                               null, null, null, 0, false));
        passwordField = new JPasswordField();
        mainPanel.add(passwordField, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1,
                                                                                      com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                                                                                      com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                                      com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                                      com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                                      null, new Dimension(150, -1),
                                                                                      null, 0, false));
        textField = new JTextField();
        mainPanel.add(textField, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 2, 1,
                                                                                  com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                                                                                  com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                                  com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                                  com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                                  null, new Dimension(150, -1), null, 0,
                                                                                  false));
        final JLabel label2 = new JLabel();
        label2.setText("PIN");
        mainPanel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1,
                                                                               com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                                                                               com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                                                                               com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                               com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                               null, null, null, 0, false));
        loginButton = new JButton();
        loginButton.setText("login");
        mainPanel.add(loginButton, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 2,
                                                                                    com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                                    com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                                    | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                                    null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
