/*
 * MainGUI.java
 *
 * Created on 2020-10-02
 *
 * Copyright (C) 2020 Volkswagen AG, All rights reserved.
 */

package gui_v3;

import atm.ATM;

import javax.swing.*;
import java.awt.*;

public class MainGUI extends GUI_v3 {
    private JPanel mainPanel;
    private JButton withdrawMoneyButton;
    private JButton depositMoneyButton;
    private JButton logoutButton;
    private JButton tranferMoneyButton;
    private JButton viewCashTransferButton;
    private JButton viewUserInformationButton;

    public MainGUI(ATM atm, JFrame parentFrame) {

        super(parentFrame, atm);

        add(mainPanel);

        logoutButton.addActionListener(e -> logout());
        withdrawMoneyButton.addActionListener(e -> goToWithdrawMenu());
        depositMoneyButton.addActionListener(e -> goToDepositMenu());
        viewUserInformationButton.addActionListener(e -> goToViewUserInformationMenu());
        tranferMoneyButton.addActionListener(e -> goToTransferMoneyMenu());
        viewCashTransferButton.addActionListener(e -> goToViewCashTransfersMenu());
    }

    private void goToViewUserInformationMenu() {

        setVisible(false);

        ViewUserInformationGUITest userInformationGUI = new ViewUserInformationGUITest(this, getAtm());
    }

    private void goToViewCashTransfersMenu() {

        setVisible(false);

        ViewCashTransferGUI viewCashTransferGUI = new ViewCashTransferGUI(this, getAtm());
    }

    private void goToTransferMoneyMenu() {

        setVisible(false);

        TransferMoneyGUI transferMoneyGUI = new TransferMoneyGUI(this, getAtm());
    }

    private void goToWithdrawMenu() {

        setVisible(false);

        WithdrawMoneyGUITest withdrawMoneyGUITest = new WithdrawMoneyGUITest(getAtm(), this);
    }

    private void goToDepositMenu() {

        setVisible(false);

        DepositMoneyGUI depositMoneyGUI = new DepositMoneyGUI(this, getAtm());
    }

    private void logout() {

        if (getAtm().logout()) {

            setVisible(false);

            getParentFrame().setVisible(true);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }
    /**
     * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR call it in your
     * code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
        withdrawMoneyButton = new JButton();
        withdrawMoneyButton.setText("Withdraw Money");
        mainPanel.add(withdrawMoneyButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 2, 1,
                                                                                            com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                                            com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                                            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                                            | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                                            null, null, null, 0,
                                                                                            false));
        logoutButton = new JButton();
        logoutButton.setText("Logout");
        mainPanel.add(logoutButton, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 2, 1,
                                                                                     com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                                     com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                                     com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                                     | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                     com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                                     null, null, null, 0, false));
        depositMoneyButton = new JButton();
        depositMoneyButton.setText("Deposit Money");
        mainPanel.add(depositMoneyButton, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 2, 1,
                                                                                           com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                                           com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                                           com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                                           | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                           com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                                           null, null, null, 0, false));
        viewCashTransferButton = new JButton();
        viewCashTransferButton.setText("View CashTransfers");
        mainPanel.add(viewCashTransferButton, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1,
                                                                                               com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                                               com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                                               com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                                               | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                               com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                                               null, null, null, 0,
                                                                                               false));
        tranferMoneyButton = new JButton();
        tranferMoneyButton.setText("Transfer Money");
        mainPanel.add(tranferMoneyButton, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1,
                                                                                           com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                                           com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                                           com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                                           | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                           com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                                           null, null, null, 0, false));
        viewUserInformationButton = new JButton();
        viewUserInformationButton.setText("View User Information");
        mainPanel.add(viewUserInformationButton, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 2, 1,
                                                                                                  com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                                                  com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                                                  com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                                                  | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                                  com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                                                  null, null, null, 0,
                                                                                                  false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
