/*
 * TransferMoneyGUI.java
 *
 * Created on 2020-09-21
 *
 * Copyright (C) 2020 Volkswagen AG, All rights reserved.
 */

package gui_v3;

import java.awt.*;
import java.math.BigDecimal;

import javax.swing.*;

import Exceptions.AccountSynchronisationException;
import atm.ATM;

public class TransferMoneyGUI extends GUI_v3 {
    private JTextField recipientIbanTextField;
    private JTextField amountTextField;
    private JTextField purposeTextField;
    private JButton backButton;
    private JButton transferButton;
    private JPanel mainPanel;

    protected TransferMoneyGUI(final JFrame parentFrame, final ATM atm) throws HeadlessException {
        super(parentFrame, atm);

        add(mainPanel);

        transferButton.addActionListener(e -> tranferMoney());
        backButton.addActionListener(e -> goBack());
    }

    private boolean textfieldsContentisNotValid() {

        if (recipientIbanTextField.getText().isEmpty() || amountTextField.getText().isEmpty() || purposeTextField
                .getText().isEmpty()) {
            return true;
        }

        if (recipientIbanTextField.getText().equals(getAtm().getLoggedInClient().getClient().getIban())) {

            showErrorDialog("Invalid content", "Can't tranfer money to yourself, ivalid iban");

            return true;
        }

        try {
            Double amount = Double.parseDouble(amountTextField.getText());

            if (amount < 0) {

                throw new NumberFormatException("negative number");
            }
        } catch (final NumberFormatException e) {
            showErrorDialog("Invalid content", "invalid amount");
            return true;
        }

        return false;
    }

    private void tranferMoney() {

        if (textfieldsContentisNotValid()) {
            return;
        }

        try {
            getAtm().transferMoney(recipientIbanTextField.getText(),
                                   BigDecimal.valueOf(Double.parseDouble(amountTextField.getText())),
                                   purposeTextField.getText());

            showInfoDialog("Success", "Money transfered");

            recipientIbanTextField.setText("");
            amountTextField.setText("");
            purposeTextField.setText("");
        } catch (final AccountSynchronisationException e) {

            showErrorDialog("Invalid content", "Can't synchronize accounts, " + e.getMessage());
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }
    /**
     * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR call it in your
     * code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(7, 5, new Insets(0, 0, 0, 0), -1, -1));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        mainPanel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(1, 4, 6, 1,
                                                                                com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                                com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL,
                                                                                1,
                                                                                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                                null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Recipient IBAN:");
        mainPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 3, 2,
                                                                               com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                                                                               com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                                                                               com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                               com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                               null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Purpose:");
        mainPanel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 2,
                                                                               com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                                                                               com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                                                                               com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                               com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                               null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Amount");
        mainPanel.add(label3, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 2,
                                                                               com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                                                                               com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                                                                               com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                               com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                               null, null, null, 0, false));
        recipientIbanTextField = new JTextField();
        mainPanel.add(recipientIbanTextField, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 3, 2,
                                                                                               com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                                                                                               com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                                               com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                                               com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                                               null,
                                                                                               new Dimension(150, -1),
                                                                                               null, 0, false));
        amountTextField = new JTextField();
        mainPanel.add(amountTextField, new com.intellij.uiDesigner.core.GridConstraints(4, 2, 1, 2,
                                                                                        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                                                                                        com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                                        null, new Dimension(150, -1),
                                                                                        null, 0, false));
        purposeTextField = new JTextField();
        mainPanel.add(purposeTextField, new com.intellij.uiDesigner.core.GridConstraints(5, 2, 1, 2,
                                                                                         com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                                                                                         com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                                         com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                                         com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                                         null, new Dimension(150, -1),
                                                                                         null, 0, false));
        backButton = new JButton();
        backButton.setText("back");
        mainPanel.add(backButton, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 1, 1,
                                                                                   com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                                   com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                                   com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                                   | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                   com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                                   null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        mainPanel.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1,
                                                                                com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                                com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                                1, null, null, null, 0, false));
        transferButton = new JButton();
        transferButton.setText("transfer");
        mainPanel.add(transferButton, new com.intellij.uiDesigner.core.GridConstraints(6, 2, 1, 2,
                                                                                       com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                                       com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                                       com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                                       | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                       com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                                       null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
